server.port=${PORT:9000}
server.error.include-stacktrace=never

# Datasource connection properties
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/jolt}
spring.datasource.name=jolt
spring.datasource.username=${DB_USERNAME:jolt_appuser}
spring.datasource.password=${DB_PASSWORD}

# JWT authorization properties
jwt.header=Authorization
jwt.base64-secret=${JWT_BASE64_SECRET}
jwt.token-validity-in-seconds=86400
jwt.token-validity-in-seconds-for-remember-me=108000

# File size properties
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Yelp Fusion API key
yelp.api.key=${YELP_API_KEY}